### ISSUE TITLE
Create a skeleton Flask project to seed repo

### ISSUE THREAD

**Issue by vivianzhhh** [Products-Squad/products#10]
As a Developer
I need some starter code
So that I can start adding features to it

Assumptions:
- We will be using Python with Flask
- This only needs to Get for now

Acceptance Criteria:
- When I issue a `git clone` on the project, I should get a minimal Flask application
- When I run `flask run`, I should have a Flask server running at localhost:5000

**Comment by LinerSu** [comment]
Manual for setting up env:
1. `git clone https://github.com/Products-Squad/products.git`
2. `cd products`
3. `python3 -m venv venv`
4. **Activate virtual env**: `. venv/bin/activate`
5. Install flask: `pip install flask`
6. **Run the project**: `flask run`
7. If it shows an error for providing the FLASK_APP, type `export FLASK_APP="src/app.py"` before running.
