### ISSUE TITLE
Set up PostgreSQL for collection product data

### ISSUE THREAD

**Issue by LinerSu** [Products-Squad/products#11]
**As a** developer
**I need** a database for storing and manipulating product info
**So that** our clients could access the product info by giving specific API request

**Assumptions:** 
Install vagrant and virtual box into my computer
Install PostgreSQL

**Acceptance Criteria:**
When I use a computer after ssh into the virtual machine
And I could write a query to request product info from database

**Comment by ianchou19** [comment]
Related plugins link: https://isudox.com/2016/07/22/guide-for-postgresql-beginners/
