### ISSUE TITLE
Create Product database and table through using PostgreSQL

### ISSUE THREAD

**Issue by ianchou19** [Products-Squad/products#25]
**As a** user
**I need** to have a product table in database
**So that** we can store and manipulate product information

**Assumptions:** 
* Run PostgreSQL through using Docker container

**Acceptance Criteria:**
When I call an API related to product resource
Then I can create/read/update/delete the corresponding data in a product table of the database

**Comment by LinerSu** [comment]
Here is one possible product JSON format for a product:
```json
{
  "id": "<int>",
  "name": "<string>",
  "stock": "<int>",
  "price": "<float>",
  "description": "<string>",
  "category": "<string>"
}
```
Maybe we can restrict the length of string inside the database. Leave any comments if you guys have any thoughts.
