### ISSUE TITLE
Create dummy data for testing

### ISSUE THREAD

**Issue by LinerSu** [Products-Squad/products#26]
**As a** developer
**I need** dummy data for products
**So that** I can test RESTful APIs in the future.

**Assumptions:** 
- Use PostgreSQL to build a database
- Python will be used for development

**Acceptance Criteria:**
Given a `dummy.csv` file inside the `psql_data` folder.
I can import it into the database if necessary.
Then I can test the APIs with those data.

**Comment by LinerSu** [comment]
Shall we consider dummy data as a JSON format? @ianchou19 @alex-s-hong @vivianzhhh

**Comment by vivianzhhh** [comment]
Maybe a csv file will be enough?
