### ISSUE TITLE
Setup continuous integration to our repository

### ISSUE THREAD

**Issue by alex-s-hong** [Products-Squad/products#74]
**As a developer** 
**I need a continuous integration tool** 
**So that our developers can verify the code integration automatically** 

**Assumptions:** 
* We have a repository
* We have Travis CI 
* We have Codecov

**Acceptance Criteria:**
Given our repository is integrated with Travis CI and Codecov
When developers check on Travis CI and Codecov's webpages
Then he/she could find the repository has already been activated in those CI tools.

**Comment by LinerSu** [comment]
Travis CI homepage:
https://travis-ci.org/Products-Squad/products
Codecov homepage:
https://codecov.io/gh/Products-Squad/products
