### ISSUE TITLE
Create a .travis.yml file and configure Travis CI to run test cases

### ISSUE THREAD

**Issue by alex-s-hong** [Products-Squad/products#75]
**As a developer**
**I need a configuration of Travis CI for our product service**  
**So that I can run the test cases and specify environment setting each time during integration**

**Assumptions:** 
- Travis CI and Codecov contain our repository
- `.travis.yml` file inside the repository

**Acceptance Criteria:**
Given `.travis.yml` file inside the repository
When developers make a pull request
Then Travis CI should automatically verify the soundness of the code committed.
In addition, Codecov will automatically generate review coverage reports.

**Comment by LinerSu** [comment]
When you create a `.travis.yml` file, please indicate this:
```
python:
- "3.6"
```
