### ISSUE TITLE
Integrate your Pull Requests with your Slack channel

### ISSUE THREAD

**Issue by LinerSu** [Products-Squad/products#77]
**As a developer**  
**I need to see each pull request in the Slack channel** 
**So that any time someone makes a pull request, the channel is notified so someone can approve it.**

**Assumptions:** 
- Slack channel for our development team

**Acceptance Criteria:**
Given a pull request,
Then slack should notify the development team immediately

**Comment by LinerSu** [comment]
Typing `/github subscribe list features` in slack channel should respond this:

This channel will get notifications from `Products-Squad/products` for: 
`issues`, `pulls`, `deployments`, `statuses`, `public`, `commits`, `releases`, `comments`

**Comment by ianchou19** [comment]
Are those GitHub's defualt notifications items (integrate with Slack)? or configured by you?

**Comment by LinerSu** [comment]
Yes, please check the product channel on slack for more details.
