### ISSUE TITLE
Need toolchain for Continuous delivery

### ISSUE THREAD

**Issue by LinerSu** [Products-Squad/products#84]
**As a developer** ...  
**I need continuous delivery pipeline** ...  
**So that our service can be assured to be reliable.** ...  

**Assumptions:** 
- Create own toolchain
- GitHub
- Deliver Pipeline

**Acceptance Criteria:**
```
Given the toolchain has created
When the developers merge branch into master branch...
Then the pipeline should automatically run through and pass the first build stage. ...
```

**Comment by alex-s-hong** [comment]
As this is the first issue, we'll add more stories for more stages such as Test, Prod, later and test it for that issue.
